services:
    client:
        build:
            context: .
            dockerfile: docker/client.Dockerfile
            args:
                VITE_SERVER_API_BASE_URL: http://localhost:5500/api/v1
        ports:
            - "5173:80"
        depends_on:
            - server
        restart: unless-stopped

    server:
        build:
            context: .
            dockerfile: docker/server.Dockerfile
        ports:
            - "5500:5500"
        env_file:
            - docker/.env
        restart: unless-stopped
